export const FETCH_EVENT_START = 'FETCH_EVENT_START';
export const FETCH_EVENT_IN_PROGRESS = 'FETCH_EVENT_IN_PROGRESS';
export const FETCH_EVENT_COMPLETE = 'FETCH_EVENT_COMPLETE';
export const FETCH_EVENT_FAILED = 'FETCH_EVENT_FAILED';